### ISSUE TITLE
Deprecated GuzzleHttp\Psr7 function API is being used and it doesn't work anymore. Please migrate to static API

### ISSUE THREAD

**Issue by timelapse999** [Azure/azure-storage-php#299]
**Which service(blob, file, queue, table) does this issue concern?**

Any one of them using Guzzle\Psr7. Issue experienced with for example blob service.

**Which version of the SDK was used?**

"microsoft/azure-storage-blob": 1.5.2

**What's the PHP/OS version?**

PHP 7.3.28
Debian Buster

**What problem was encountered?**

For example: 

`Error: Call to undefined function GuzzleHttp\\Psr7\\stream_for() in /microsoft/azure-storage-blob/src/Blob/BlobRestProxy.php:1837`

It seems azure-storage-php is still using a function API for Guzzle PSR-7, but that has been removed and replaced with static API.

The code on that line, which doesn't work:

`$body = Psr7\stream_for($content);`

Using this works:

`$body = Utils::streamFor($content);`

(after importing GuzzleHttp\Psr7\Utils;)

**Have you found a mitigation/solution?**

Migrate to static API by using a migration table found here: [Guzzle PSR-7 Upgrading from Function API](https://github.com/guzzle/psr7#upgrading-from-function-api)

**Comment by timelapse999** [comment]
This happens if guzzlehttp/guzzle 7.0 is used and guzzlehttp/psr7 is upgraded to 2.0

**Comment by balasta75** [comment]
Hi,

When do you will update the code to be able to use new version of guzzlehttp/psr-7 ? 

Thanks

**Comment by balasta75** [comment]
Or can you update your composer.json to use the good versions of Guzzle ?

**Comment by ScottHelme** [comment]
Registering our interest in this issue too, we're currently experiencing the same issue.

**Comment by spaze** [comment]
FYI, there's an attempted fix in #302 by @galvani.

The problem can be also worked around by locking PSR2 to 1.7 (or even 1.0) in `composer.json` like

```
"guzzlehttp/psr7": "^1.7",
```

**Comment by reconstrukt** [comment]
Same problem here. +1
But, can confirm that the workaround from @spaze above _does work_ as a temp solve for now

**Comment by danpowley-hee** [comment]
Same problem here, after composer update: `Upgrading guzzlehttp/psr7 (1.8.2 => 2.0.0)`

Error message:
`Call to undefined function GuzzleHttp\Psr7\build_query() at /app/vendor/microsoft/azure-storage-common/src/Common/Internal/ServiceRestProxy.php:309`

Work around:
As per spaze suggestion above, we have now also limited guzzlehttp/psr7 to 1.8 explicitly in composer.json to keep things working.
`"guzzlehttp/psr7": "^1.8",`

**Comment by galvani** [comment]
it is fixed here: https://github.com/Azure/azure-storage-php/pull/302

**Comment by neoacevedo** [comment]
@galvani I'm sorry but it isn't fixed yet. Just today, I ran the composer update and I got this issue.

**Comment by mfpx** [comment]
Not fixed, still ongoing on our client's project.

**Comment by spaze** [comment]
@mfpx @neoacevedo The fix has not been released yet. In fact, there was no release since December 2020, check the [Releases page](https://github.com/Azure/azure-storage-php/releases). You can "Watch" the repository to be informed about new releases (and you can select Releases only under Custom).

**Comment by jeffpaul** [comment]
@spaze @katmsft we're utilizing this library as part of the [Microsoft Azure Storage for WordPress plugin](https://wordpress.org/plugins/windows-azure-storage/) ([see source](https://github.com/10up/windows-azure-storage)) and are currently blocked by getting this issue closed via a release for the already merged PR #302.  Any ETA you can provide for an upcoming release will help us plan our downstream communications to users within the WordPress ecosystem.  Many thanks!
